// Code generated by protoc-gen-go. DO NOT EDIT.
// source: uptalk.proto

/*
Package uptalk is a generated protocol buffer package.

It is generated from these files:
	uptalk.proto

It has these top-level messages:
	Chat
	Message
	User
*/
package uptalk

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Chat struct {
	Name     string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Members  []*User    `protobuf:"bytes,4,rep,name=members" json:"members,omitempty"`
	Messages []*Message `protobuf:"bytes,3,rep,name=messages" json:"messages,omitempty"`
}

func (m *Chat) Reset()                    { *m = Chat{} }
func (m *Chat) String() string            { return proto.CompactTextString(m) }
func (*Chat) ProtoMessage()               {}
func (*Chat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Chat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Chat) GetMembers() []*User {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Chat) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Message struct {
	Text   string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	Author *User  `protobuf:"bytes,3,opt,name=author" json:"author,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetAuthor() *User {
	if m != nil {
		return m.Author
	}
	return nil
}

type User struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Chat)(nil), "Chat")
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*User)(nil), "User")
}

func init() { proto.RegisterFile("uptalk.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2d, 0x28, 0x49,
	0xcc, 0xc9, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x4a, 0xe4, 0x62, 0x71, 0xce, 0x48, 0x2c,
	0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02,
	0xb3, 0x85, 0xe4, 0xb9, 0xd8, 0x73, 0x53, 0x73, 0x93, 0x52, 0x8b, 0x8a, 0x25, 0x58, 0x14, 0x98,
	0x35, 0xb8, 0x8d, 0x58, 0xf5, 0x42, 0x8b, 0x53, 0x8b, 0x82, 0x60, 0xa2, 0x42, 0x2a, 0x5c, 0x1c,
	0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0xc5, 0x12, 0xcc, 0x60, 0x15, 0x1c, 0x7a, 0xbe, 0x10,
	0x81, 0x20, 0xb8, 0x8c, 0x92, 0x0d, 0x17, 0x3b, 0x54, 0x10, 0x64, 0x4b, 0x49, 0x6a, 0x45, 0x09,
	0xcc, 0x16, 0x10, 0x5b, 0x48, 0x96, 0x8b, 0x2d, 0xb1, 0xb4, 0x24, 0x23, 0xbf, 0x48, 0x82, 0x59,
	0x81, 0x11, 0x61, 0x09, 0x54, 0x50, 0x49, 0x8a, 0x8b, 0x05, 0xc4, 0xc7, 0xe6, 0xc0, 0x24, 0x36,
	0xb0, 0x1f, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x86, 0x27, 0x27, 0x38, 0xd3, 0x00, 0x00,
	0x00,
}
